# Generated by Django 3.2.3 on 2021-05-19 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=150)),
                ('passo', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'login',
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('uname', models.CharField(max_length=150)),
                ('phno', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('passo', models.CharField(max_length=150)),
                ('upass', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'register',
            },
        ),
    ]
